export * from "./configs/node.js"
export * from "./configs/ts-node.js"
export * from "./configs/node-jest.js"
export * from "./configs/react.js"
export * from "./configs/react-jest.js"
export * from "./configs/dev-files.js"
